version: 2
jobs:
    one:
        docker:
            - image: circleci/python:3.5.5
        steps:
            - checkout
            - run: echo "hello world"
    two:
        docker:
            - image: circleci/python:3.5.5
        steps:
            - checkout
            - run: echo  "most importantly hello you"
    workflows:
        version: 2
        one_and_two:
            jobs:
                -one
                -two
